stages:
  - lint

lint:
  stage: lint
  image: python:3.11-slim
  tags:
    - docker
    - python
  script:
    - pip install --upgrade pip
    - pip install pylint
    - pip install -r requirements.txt
    - pylint --rcfile=.pylintrc $(find . -name "*.py")
