stages:
  - lint

lint:
  stage: lint
  image: python:3.11-slim
  tags:
    - docker
    - python
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install pylint
    - pip install boto3
    - pip install pyvmomi
    - pip install yaml
    - pylint --rcfile=.pylintrc $(find . -type f -name "*.py" -not -path "./venv/*")
