stages:
  - lint

lint:
  stage: lint
  image: python:3.11-slim
  tags:
    - docker
    - python
  script:
    - pip install pylint
    - pylint --rcfile=.pylintrc --fail-under=8.0 $(find . -name "*.py")
