stages:
  - lint

lint:
  stage: lint
  image: python:3.11-slim
  tags:
    - docker
    - python
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --no-cache-dir --upgrade pip pylint boto3 pyvmomi pyyaml
    - pylint --rcfile=.pylintrc $(find . -type f -name "*.py" -not -path "./venv/*")
